use_frameworks!

target 'lvPodLibrary22_Example' do
  pod 'lvPodLibrary22', :path => '../'

  target 'lvPodLibrary22_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
